### PR TITLE
fix: allow after instructions for resumable uploads in a single chunk

### LINKED ISSUE #510: PUTing a full object to a resumable session does not trigger after instructions
PUTing a full object to a resumable session does not trigger `after` instructions such as `return-503-after-256K`[1].

`after` instructions appear to apply to the next request[2].

#### Environment details

  - Package version: `gcr.io/cloud-devrel-public-resources/storage-testbench:v0.36.0`

#### Steps to reproduce

```bash
# start the container
docker run --rm -d --name repro gcr.io/cloud-devrel-public-resources/storage-testbench:v0.36.0
# create a bucket
xh --print=h :9000/storage/v1/b project==project-id name=bucket1
# create the resumable upload session
{ uploadId=$(xh --print=h POST :9000/upload/storage/v1/b/bucket1/o name==object1 uploadType==resumable | tee /dev/fd/3 | grep -i 'Location:' | cut -b11-) ; } 3>&1
# upload 768KiB of data and finalize the session
dd ibs=262144 count=3 if=/dev/urandom | xh --print=Hh PUT "$uploadId" Content-Range:'bytes 0-786431/786432' x-goog-emulator-instructions:return-503-after-256K
# stop the docker container
docker kill repro
```

[1] https://gist.github.com/BenWhitehead/07b65f51ac6e0f6421d0a7f41a4d5433#file-01_result-txt-L12-L28
[2] https://gist.github.com/BenWhitehead/07b65f51ac6e0f6421d0a7f41a4d5433#file-02_result-txt-L38-L53

### PR DESCRIPTION
**Pull request by cojenco**
Fixes #510
- allow `return-X-after-YK` and `x-goog-emulator-instructions:return-503-after-256K` forced failures instructions for resumable uploads in both multiple chunks and a single chunk
- add support to testbench for uploads to ignore request bytes already persisted, in align with GCS

**[ASK]
Given that languages have different implementations on restarting an interrupted upload, verify language (conformance) tests are not adversely impacted by these new changes**

**integration tests & conformance tests**

- [x] c++
- [x] c#
- [x] go
- [x] java
- [x] node.js
- [x] php
- [x] python 
- [x] ruby
- [x] testbench unit tests

### CODE REVIEW

**Comment by coryan** [comment]
This seems to break the C++ tests:

https://github.com/googleapis/google-cloud-cpp/pull/12069

Specifically these two tests:

https://github.com/googleapis/google-cloud-cpp/blob/576ea4680c54a9c3936481f43cc35072f9bd17f6/google/cloud/storage/tests/object_hash_integration_test.cc#L234-L257

https://github.com/googleapis/google-cloud-cpp/blob/576ea4680c54a9c3936481f43cc35072f9bd17f6/google/cloud/storage/tests/object_checksum_integration_test.cc#L238-L260

Both use `x-goog-emulator-instructions: inject-upload-data-error`, but fail with a fairly strange error.

```
2023-07-11T12:59:42.940753097Z [INFO] <140502397696384> UploadChunk() << UploadChunkRequest={upload_session_url=http://localhost:34887/upload/storage/v1/b/gcs-grpc-team-cloud-cpp-testing-bucket/o?uploadType=resumable&upload_id=4fb4efcfeb2deb52eb99f86617e5124336d7c2dfe2bc3a655a6eb3a4f0f8c5ad, range=<Content-Range: bytes 0-446/447>, known_object_hashes={}, x-goog-emulator-instructions: inject-upload-data-error, payload={{Lorem ipsum dolor sit amet, consectetur adipiscing.elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut e...<truncated>...}}} (/workspace/google/cloud/storage/internal/logging_client.cc:44)
2023-07-11T12:59:42.952790037Z [INFO] <140502397696384> UploadChunk() >> status={UNKNOWN: PerformWork() - CURL error [1]=Unsupported protocol} (/workspace/google/cloud/storage/internal/logging_client.cc:49)
```

**Comment by cojenco** [comment]
We also see failed tests in Node.js with resumable upload request headers content-range set to`'bytes 0-*/*'`. This seems to be related to case handling in `chunk_last_byte`. Looking into this furthermore.
https://github.com/googleapis/storage-testbench/blob/a5a6592767799dc88122978bc5e3d04d0e6b2377/testbench/rest_server.py#L1007-L1009

**Comment by cojenco** [comment]
Hi @ddelgrosso1 the node conformance tests now pass in my local dev environment. Could you help verify again when you have a chance, thanks!

**Comment by cojenco** [comment]
Hi @coryan I believe the two failed tests are related. I've updated the PR to only inspect after-bytes instructions and added a unit test. Could you help run the C++ test suite again when you have a chance, thanks!

**Comment by coryan** [comment]
The C++ tests are now passing: https://github.com/googleapis/google-cloud-cpp/pull/12069 :shipit:

**Review by coryan — APPROVED** [review]

**Comment by cojenco** [comment]
Update - confirmed that no language test is adversely impacted by this PR. Merging and cutting a new release tag shortly

**Pull request merged**
