### PR TITLE
feat: replace `gunicorn` with `uvicorn` to support Windows

### PR DESCRIPTION
**Pull request by anuragsrivstv**
This PR contains changes which will make storage test bench windows compatible.
- Replaced gunicorn command with uvicorn to run the test bench. Uvicorn is windows compatible.
- Done changes to convert wsgi server into an asgi server as uvicorn needs asgi server.
- Updated corresponding python test files

- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by anuragsrivstv** [comment]
Some checks are failing right now, looking into it.

**Comment by BenWhitehead** [comment]
I checked out your branch and tried running the java conformance suite against it.

First I needed to change the `CMD` in the `Dockerfile` to work with the new flags.

```diff
Index: Dockerfile
<+>UTF-8
===================================================================
diff --git a/Dockerfile b/Dockerfile
--- a/Dockerfile	(revision 0858d6c0e9ca790114b75598e14baf27b9584855)
+++ b/Dockerfile	(date 1664922983461)
@@ -20,9 +20,8 @@
 
 RUN python3 -m pip install -e .
 
-CMD ["gunicorn", \
-      "--bind", "0.0.0.0:9000", \
-      "--worker-class", "sync", \
-      "--threads", "10", \
-      "--access-logfile", "-", \
-      "testbench:run()"]
+CMD ["uvicorn", \
+      "testbench:run", \
+      "--host", "0.0.0.0", "--port", "9000", \
+      "--access-log"]
+

```

During test run, it seems that creating a bucket is failing due to a JSON Decoding error (full request collapsed below)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/storage-testbench/./testbench/common.py", line 797, in wrapper
    return response_handler(func(*args, **kwargs))
  File "/opt/storage-testbench/./testbench/rest_server.py", line 216, in bucket_insert
    bucket, projection = gcs_type.bucket.Bucket.init(flask.request, None)
  File "/opt/storage-testbench/./gcs/bucket.py", line 264, in init
    metadata = cls.__preprocess_rest(json.loads(request.data))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

<details>
<summary>Full request log</summary>

```
2022-10-04 18:42:21,572 CONFIG   com.google.api.client.http.HttpTransport           - -------------- REQUEST  --------------
POST http://localhost:9000/storage/v1/b?project=conformance-tests&projection=full
Accept-Encoding: gzip
User-Agent: non-test/ (TestRetryConformance/1-[return-503_return-503]-storage.objects.get-41) java-conformance-tests/ gcloud-java/ Google-API-Java-Client/2.0.0 Google-HTTP-Java-Client/1.42.2 (gzip)
x-goog-api-client: gl-java/1.8.0 gdcl/2.0.0 linux/5.18.16 gccl-invocation-id/160ef385-82d4-4831-b207-41584f7782ee
Content-Type: application/json; charset=UTF-8
Content-Encoding: gzip
 
2022-10-04 18:42:21,572 CONFIG   com.google.api.client.http.HttpTransport           - curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'User-Agent: non-test/ (TestRetryConformance/1-[return-503_return-503]-storage.objects.get-41) java-conformance-tests/ gcloud-java/ Google-API-Java-Client/2.0.0 Google-HTTP-Java-Client/1.42.2 (gzip)' -H 'x-goog-api-client: gl-java/1.8.0 gdcl/2.0.0 linux/5.18.16 gccl-invocation-id/160ef385-82d4-4831-b207-41584f7782ee' -H 'Content-Type: application/json; charset=UTF-8' -H 'Content-Encoding: gzip' -d '@-' -- 'http://localhost:9000/storage/v1/b?project=conformance-tests&projection=full' << $$$ 
2022-10-04 18:42:21,578 CONFIG   com.google.api.client.http.HttpTransport           - Total: 63 bytes 
2022-10-04 18:42:21,579 CONFIG   com.google.api.client.http.HttpTransport           - {"name":"224219_s001-503_503-m041_bkt1","retentionPolicy":null} 
2022-10-04 18:42:21,582 CONFIG   com.google.api.client.http.HttpTransport           - -------------- RESPONSE --------------
HTTP/1.1 500 Internal Server Error
date: Tue, 04 Oct 2022 22:42:21 GMT
content-length: 1281
server: uvicorn
content-type: application/json
 
2022-10-04 18:42:21,590 CONFIG   com.google.api.client.http.HttpTransport           - Total: 1,281 bytes 
2022-10-04 18:42:21,591 CONFIG   com.google.api.client.http.HttpTransport           - {"error":{"code":500,"message":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/site-packages/flask/app.py\", line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/opt/storage-testbench/./testbench/common.py\", line 797, in wrapper\n    return response_handler(func(*args, **kwargs))\n  File \"/opt/storage-testbench/./testbench/rest_server.py\", line 216, in bucket_insert\n    bucket, projection = gcs_type.bucket.Bucket.init(flask.request, None)\n  File \"/opt/storage-testbench/./gcs/bucket.py\", line 264, in init\n    metadata = cls.__preprocess_rest(json.loads(request.data))\n  File \"/usr/local/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"}}
 
```
</details>

**Comment by anuragsrivstv** [comment]
> 


> I checked out your branch and tried running the java conformance suite against it.
> 
> First I needed to change the `CMD` in the `Dockerfile` to work with the new flags.
> 
> ```diff
> Index: Dockerfile
> <+>UTF-8
> ===================================================================
> diff --git a/Dockerfile b/Dockerfile
> --- a/Dockerfile	(revision 0858d6c0e9ca790114b75598e14baf27b9584855)
> +++ b/Dockerfile	(date 1664922983461)
> @@ -20,9 +20,8 @@
>  
>  RUN python3 -m pip install -e .
>  
> -CMD ["gunicorn", \
> -      "--bind", "0.0.0.0:9000", \
> -      "--worker-class", "sync", \
> -      "--threads", "10", \
> -      "--access-logfile", "-", \
> -      "testbench:run()"]
> +CMD ["uvicorn", \
> +      "testbench:run", \
> +      "--host", "0.0.0.0", "--port", "9000", \
> +      "--access-log"]
> +
> ```
> 
> During test run, it seems that creating a bucket is failing due to a JSON Decoding error (full request collapsed below)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/opt/storage-testbench/./testbench/common.py", line 797, in wrapper
>     return response_handler(func(*args, **kwargs))
>   File "/opt/storage-testbench/./testbench/rest_server.py", line 216, in bucket_insert
>     bucket, projection = gcs_type.bucket.Bucket.init(flask.request, None)
>   File "/opt/storage-testbench/./gcs/bucket.py", line 264, in init
>     metadata = cls.__preprocess_rest(json.loads(request.data))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> Full request log


Thanks Ben, I'll look into it.

**Comment by anuragsrivstv** [comment]
Closing this. Will raise another PR.

**Pull request closed without merging**
